use RBS::AST::Members::MethodDefinition::Overload

module RBS
  module Inline
    module AST
      module Members
        type ruby = RubyDef | RubyAlias | RubyMixin | RubyAttr | RubyPublic | RubyPrivate

        type rbs = RBSDef | RBSAlias | RBSAttr

        type t = ruby | rbs

        class RBSDef < Base
        end

        class RBSAlias < Base
        end

        class RBSAttr < Base
        end
      end
    end
  end
end
