module RBS
  module Inline
    module AST
      class Tree
        type token = [Symbol, String]

        type tree = token | Tree | Types::t | MethodType | nil

        attr_reader trees: Array[tree]

        attr_reader type: Symbol

        def initialize: (Symbol type) -> void

        def <<: (tree) -> self

        def non_trivia_trees: () -> Array[tree]

        def nth_token: (Integer) -> token?

        def nth_token?: (Integer) -> token?

        def nth_token!: (Integer) -> token

        def nth_tree: (Integer) -> Tree?

        def nth_tree?: (Integer) -> Tree?

        def nth_tree!: (Integer) -> Tree

        def nth_type: (Integer) -> Types::t?

        def nth_type?: (Integer) -> Types::t?

        def nth_type!: (Integer) -> Types::t

        def nth_method_type: (Integer) -> MethodType?

        def nth_method_type?: (Integer) -> MethodType?

        def nth_method_type!: (Integer) -> MethodType

        def to_s: () -> String
      end
    end
  end
end
