module RBS
  module Inline
    type token = [Symbol, String]

    VERSION: String

    module AST
      module Declarations
        type t = ClassDecl | ModuleDecl | ConstantDecl

        interface _WithComments
          def comments: () -> AnnotationParser::ParsingResult?
        end
      end

      module Annotations
        type t = VarType
               | ReturnType
               | Use
               | Inherits
               | Generic
               | ModuleSelf
               | Skip
               | Assertion
               | Application
               | RBSAnnotation
               | Override
             #  | Def
             #  | AttrReader | AttrWriter | AttrAccessor
             #  | Include | Extend | Prepend
             #  | Alias
     end
    end
  end
end
